project:
  type: website
  output-dir: docs

website:
  title: "STA 9750 Submission Material"
  description:
    Course Projects for STA 9750 at Baruch College
  site-url: "https://laurenrichbetch.github.io/STA9750-2026-SPRING/"
  navbar:
    background: primary
    search: false
    left:
      - href: mp02.qmd
        text: MP02

format:
  html:
    theme: lux
    toc: false

editor:
  mode: source